/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonegenerator;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class ViewGeneratedPhones extends javax.swing.JFrame {

    /**
     * Creates new form ViewGeneratedPhones
     */
    String n="";
    public ViewGeneratedPhones(File f) {

           
        initComponents();
         Image image =Toolkit.getDefaultToolkit().getImage(getClass().getResource("teleic.png"));
//         ImageIcon io=new ImageIcon(getClass().getResource("teleic.png").getFile());
        this.setIconImage(image);
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         this.setTitle("View Phone Numbers");
         System.out.println(f.getPath());
         String gg=f.getName();
        // gg=gg.substring(gg.lastIndexOf("\\"));
         String nameclient=gg;
         String nam=nameclient.substring(0,nameclient.indexOf("."));
         n=nam.substring(0,nam.length()-4);
                   this.addWindowListener(new WindowAdapter() {
    public void windowClosing(WindowEvent we)
    { 
        String ObjButtons[] = {"Yes","No"};
        UIManager UI=new UIManager();
 UI.put("OptionPane.background", Color.GRAY);
 UI.put("Panel.background", Color.GRAY);
        int PromptResult = JOptionPane.showOptionDialog(null,"Are you sure you want to exit?","Closing Check",JOptionPane.DEFAULT_OPTION,JOptionPane.WARNING_MESSAGE,null,ObjButtons,ObjButtons[1]);
       
        if(PromptResult==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }
});
         
         ///
        
  ///////       
          try {
			FileInputStream fis = new FileInputStream(f);
			BufferedReader br = new BufferedReader(new InputStreamReader(fis));
                        String firstline= br.readLine().trim();
                        String[] columnsname =firstline.split(" ");
                        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                        Object[] tableLines =br.lines().toArray();
                        String[] dataRow1 =firstline.split(" ");
                         model.addRow(dataRow1);
                        for(int i=0;i<tableLines.length;i++)
                        {
                            String line =tableLines[i].toString().trim();
                            String[] dataRow =line.split(" ");
                            model.addRow(dataRow);
                        
                        }
                        
			
			br.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jTable1.setBackground(new java.awt.Color(0, 51, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phone Number"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("export contact");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("toback");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton1)
                .addGap(41, 41, 41)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //  TODO add your handling code here:
         FileOutputStream fop = null;
         File f=null;
         int lentable=jTable1.getRowCount();
         int j=0;
         while (j < lentable) {
               
             
         
        try {
            // TODO add your handling code here:
            String phonenumber =(String) jTable1.getModel().getValueAt(j, 0);
            String Name = n+phonenumber;
            //String phonenumber = jTextField2.getText();
                   File fol=new File(System.getProperty("user.home")+File.separatorChar+"My Documents"+"\\"+"Phone Generator"+"\\"+"mycontacts\\");
fol.mkdir();
             f=new File(fol.getPath()+"\\"+Name+".vcf");
            fop = new FileOutputStream(f);
            if(f.exists())
            {

                
                String str="BEGIN:VCARD\n" +
                         "VERSION:2.1\n" +
                         "N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:;"+Name+";;;\n" +
                         "FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:"+Name+"\n" +
                         "TEL;CELL:"+phonenumber+"\n" +
                         "END:VCARD";
                fop.write(str.getBytes());
                //Now read the content of the vCard after writing data into it
                BufferedReader br = null;
                String sCurrentLine;
                
                br = new BufferedReader(new FileReader(f));
                
                while ((sCurrentLine = br.readLine()) != null)
                {
                    System.out.println(sCurrentLine);
                }
                //close the output stream and buffer reader
                fop.flush();
                fop.close();
                System.out.println("The data has been written");
            } else
                System.out.println("This file does not exist");
            fop.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ViewGeneratedPhones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ViewGeneratedPhones.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
         
        }
           j++;
            }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Generate g = new Generate();
            g.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
